-- local hit_effects = require("__base__.prototypes.entity.hit-effects")
local sounds = require("__base__.prototypes.entity.sounds")

data:extend({
  {
    type = "assembling-machine",
    name = "kr-singularity-generator",
    icon = "__Krastorio2Assets__/icons/entities/intergalactic-transceiver.png",
    icon_size = 64,
    icon_mipmaps = 4,
    flags = { "not-rotatable", "placeable-neutral", "placeable-player", "player-creation" },
    -- minable = { mining_time = 0.2, result = "kr-singularity-generator" },
    max_health = 350,
    impact_category = "metal",
    -- corpse = "assembling-machine-2-remnants",
    -- dying_explosion = "assembling-machine-2-explosion",
    -- circuit_wire_max_distance = assembling_machine_circuit_wire_max_distance,
    -- circuit_wire_connection_points = circuit_connector_definitions["assembling-machine"].points,
    -- circuit_connector_sprites = circuit_connector_definitions["assembling-machine"].sprites,
    -- alert_icon_shift = util.by_pixel(-3, -12),
    -- resistances = {
    --   {
    --     type = "fire",
    --     percent = 70,
    --   },
    -- },
    collision_box = { { -6, -5.4 }, { 6, 5.4 } },
    selection_box = { { -6, -5.5 }, { 6, 5.5 } },
    -- damaged_trigger_effect = hit_effects.entity(),
    -- fast_replaceable_group = "kr-singularity-generator",
    animation = {
      layers = {
        {
          filename = kr_entities_path .. "intergalactic-transceiver/intergalactic-transceiver.png",
          width = 400,
          height = 400,
          frame_count = 1,
          repeat_count = 60,
          shift = { 0, -0.8 },
          animation_speed = 0.7,
          hr_version = {
            filename = kr_entities_path .. "intergalactic-transceiver/hr-intergalactic-transceiver.png",
            width = 800,
            height = 800,
            scale = 0.5,
            frame_count = 1,
            repeat_count = 60,
            animation_speed = 0.7,
            shift = { 0, -0.8 },
          },
        },
        {
          filename = kr_entities_path .. "intergalactic-transceiver/intergalactic-transceiver-sh.png",
          priority = "low",
          width = 434,
          height = 313,
          frame_count = 1,
          repeat_count = 60,
          draw_as_shadow = true,
          animation_speed = 0.7,
          shift = { 0.52, 0.5 },
          hr_version = {
            filename = kr_entities_path .. "intergalactic-transceiver/hr-intergalactic-transceiver-sh.png",
            priority = "low",
            width = 867,
            height = 626,
            scale = 0.5,
            frame_count = 1,
            repeat_count = 60,
            draw_as_shadow = true,
            animation_speed = 0.7,
            shift = { 0.52, 0.5 },
          },
        },
        {
          filename = kr_entities_path .. "intergalactic-transceiver/intergalactic-transceiver-charging.png",
          priority = "high",
          width = 400,
          height = 400,
          frame_count = 60,
          line_length = 10,
          animation_speed = 0.7,
          shift = { 0, -0.8 },
          draw_as_glow = true,
          hr_version = {
            filename = kr_entities_path .. "intergalactic-transceiver/hr-intergalactic-transceiver-charging.png",
            priority = "high",
            width = 800,
            height = 800,
            scale = 0.5,
            frame_count = 60,
            line_length = 10,
            animation_speed = 0.7,
            shift = { 0, -0.8 },
            draw_as_glow = true,
          },
        },
        {
          filename = kr_entities_path .. "intergalactic-transceiver/intergalactic-transceiver-light.png",
          priority = "high",
          width = 400,
          height = 400,
          frame_count = 1,
          repeat_count = 60,
          shift = { 0, -0.8 },
          draw_as_light = true,
          animation_speed = 0.7,
          hr_version = {
            filename = kr_entities_path .. "intergalactic-transceiver/hr-intergalactic-transceiver-light.png",
            priority = "high",
            width = 800,
            height = 800,
            scale = 0.5,
            frame_count = 1,
            repeat_count = 60,
            animation_speed = 0.7,
            shift = { 0, -0.8 },
            draw_as_light = true,
          },
        },
        {
          filename = kr_entities_path .. "intergalactic-transceiver/intergalactic-transceiver-charging-light.png",
          priority = "high",
          width = 400,
          height = 400,
          frame_count = 60,
          line_length = 10,
          animation_speed = 0.7,
          shift = { 0, -0.8 },
          draw_as_light = true,
          hr_version = {
            filename = kr_entities_path .. "intergalactic-transceiver/hr-intergalactic-transceiver-charging-light.png",
            priority = "high",
            width = 800,
            height = 800,
            scale = 0.5,
            frame_count = 60,
            line_length = 10,
            animation_speed = 0.7,
            shift = { 0, -0.8 },
            draw_as_light = true,
          },
        },
      },
    },
    open_sound = sounds.machine_open,
    close_sound = sounds.machine_close,
    working_sound = {
      filename = kr_buildings_sounds_path .. "intergalactic-transceiver-charge.ogg",
      volume = 1.2,
      fade_in_ticks = 4,
      fade_out_ticks = 20,
    },

    crafting_categories = { "kr-singularity" },
    crafting_speed = 1,
    energy_source = {
      type = "fluid",
      fluid_box = {

        production_type = "input",
        -- pipe_picture = assembler2pipepictures(),
        pipe_covers = _ENV.pipecoverspictures(),
        base_area = 10,
        base_level = -1,
        pipe_connections = {
          { type = "input-output", position = { -1.5, -6 } },
          { type = "input-output", position = { 1.5, -6 } },
        },
        secondary_draw_orders = { north = -1 },
        filter = "matter",
      },
      effectivity = 0.8,
    },
    energy_usage = "100kW",
    module_specification = {
      module_slots = 0,
    },
    allowed_effects = {},
  },
  -- {
  --   type = "assembling-machine",
  --   name = "kr-singularity-assembler",
  --   localised_name = { "entity-name.kr-singularity-generator" },
  --   icon = "__Krastorio2Assets__/icons/entities/intergalactic-transceiver.png",
  --   icon_size = 64,
  --   icon_mipmaps = 4,
  --   flags = { "not-rotatable", "placeable-neutral", "placeable-player", "player-creation" },
  --   -- minable = { mining_time = 0.2, result = "kr-singularity-generator" },
  --   max_health = 350,
  --   impact_category = "metal",
  --   -- corpse = "assembling-machine-2-remnants",
  --   -- dying_explosion = "assembling-machine-2-explosion",
  --   -- circuit_wire_max_distance = assembling_machine_circuit_wire_max_distance,
  --   -- circuit_wire_connection_points = circuit_connector_definitions["assembling-machine"].points,
  --   -- circuit_connector_sprites = circuit_connector_definitions["assembling-machine"].sprites,
  --   -- alert_icon_shift = util.by_pixel(-3, -12),
  --   -- resistances = {
  --   --   {
  --   --     type = "fire",
  --   --     percent = 70,
  --   --   },
  --   -- },
  --   collision_mask = {},
  --   collision_box = { { -6, -5.4 }, { 6, 5.4 } },
  --   selection_box = { { -6, -5.5 }, { 6, 5.5 } },
  --   -- damaged_trigger_effect = hit_effects.entity(),
  --   -- fast_replaceable_group = "kr-singularity-generator",
  --   -- animation = {
  --   --   layers = {
  --   --     {
  --   --       filename = kr_entities_path .. "intergalactic-transceiver/intergalactic-transceiver.png",
  --   --       width = 400,
  --   --       height = 400,
  --   --       frame_count = 1,
  --   --       repeat_count = 60,
  --   --       shift = { 0, -0.8 },
  --   --       animation_speed = 0.7,
  --   --       hr_version = {
  --   --         filename = kr_entities_path .. "intergalactic-transceiver/hr-intergalactic-transceiver.png",
  --   --         width = 800,
  --   --         height = 800,
  --   --         scale = 0.5,
  --   --         frame_count = 1,
  --   --         repeat_count = 60,
  --   --         animation_speed = 0.7,
  --   --         shift = { 0, -0.8 },
  --   --       },
  --   --     },
  --   --     {
  --   --       filename = kr_entities_path .. "intergalactic-transceiver/intergalactic-transceiver-sh.png",
  --   --       priority = "low",
  --   --       width = 434,
  --   --       height = 313,
  --   --       frame_count = 1,
  --   --       repeat_count = 60,
  --   --       draw_as_shadow = true,
  --   --       animation_speed = 0.7,
  --   --       shift = { 0.52, 0.5 },
  --   --       hr_version = {
  --   --         filename = kr_entities_path .. "intergalactic-transceiver/hr-intergalactic-transceiver-sh.png",
  --   --         priority = "low",
  --   --         width = 867,
  --   --         height = 626,
  --   --         scale = 0.5,
  --   --         frame_count = 1,
  --   --         repeat_count = 60,
  --   --         draw_as_shadow = true,
  --   --         animation_speed = 0.7,
  --   --         shift = { 0.52, 0.5 },
  --   --       },
  --   --     },
  --   --     {
  --   --       filename = kr_entities_path .. "intergalactic-transceiver/intergalactic-transceiver-charging.png",
  --   --       priority = "high",
  --   --       width = 400,
  --   --       height = 400,
  --   --       frame_count = 60,
  --   --       line_length = 10,
  --   --       animation_speed = 0.7,
  --   --       shift = { 0, -0.8 },
  --   --       draw_as_glow = true,
  --   --       hr_version = {
  --   --         filename = kr_entities_path .. "intergalactic-transceiver/hr-intergalactic-transceiver-charging.png",
  --   --         priority = "high",
  --   --         width = 800,
  --   --         height = 800,
  --   --         scale = 0.5,
  --   --         frame_count = 60,
  --   --         line_length = 10,
  --   --         animation_speed = 0.7,
  --   --         shift = { 0, -0.8 },
  --   --         draw_as_glow = true,
  --   --       },
  --   --     },
  --   --     {
  --   --       filename = kr_entities_path .. "intergalactic-transceiver/intergalactic-transceiver-light.png",
  --   --       priority = "high",
  --   --       width = 400,
  --   --       height = 400,
  --   --       frame_count = 1,
  --   --       repeat_count = 60,
  --   --       shift = { 0, -0.8 },
  --   --       draw_as_light = true,
  --   --       animation_speed = 0.7,
  --   --       hr_version = {
  --   --         filename = kr_entities_path .. "intergalactic-transceiver/hr-intergalactic-transceiver-light.png",
  --   --         priority = "high",
  --   --         width = 800,
  --   --         height = 800,
  --   --         scale = 0.5,
  --   --         frame_count = 1,
  --   --         repeat_count = 60,
  --   --         animation_speed = 0.7,
  --   --         shift = { 0, -0.8 },
  --   --         draw_as_light = true,
  --   --       },
  --   --     },
  --   --     {
  --   --       filename = kr_entities_path .. "intergalactic-transceiver/intergalactic-transceiver-charging-light.png",
  --   --       priority = "high",
  --   --       width = 400,
  --   --       height = 400,
  --   --       frame_count = 60,
  --   --       line_length = 10,
  --   --       animation_speed = 0.7,
  --   --       shift = { 0, -0.8 },
  --   --       draw_as_light = true,
  --   --       hr_version = {
  --   --         filename = kr_entities_path .. "intergalactic-transceiver/hr-intergalactic-transceiver-charging-light.png",
  --   --         priority = "high",
  --   --         width = 800,
  --   --         height = 800,
  --   --         scale = 0.5,
  --   --         frame_count = 60,
  --   --         line_length = 10,
  --   --         animation_speed = 0.7,
  --   --         shift = { 0, -0.8 },
  --   --         draw_as_light = true,
  --   --       },
  --   --     },
  --   --   },
  --   -- },
  --   open_sound = sounds.machine_open,
  --   close_sound = sounds.machine_close,
  --   -- working_sound = {
  --   --   filename = kr_buildings_sounds_path .. "intergalactic-transceiver-charge.ogg",
  --   --   volume = 1.2,
  --   --   fade_in_ticks = 4,
  --   --   fade_out_ticks = 20,
  --   -- },

  --   crafting_categories = { "kr-singularity" },
  --   crafting_speed = 2,
  --   energy_source = {
  --     type = "electric",
  --     usage_priority = "secondary-input",
  --     emissions_per_minute = 3,
  --   },
  --   energy_usage = "5GW",
  --   module_specification = {
  --     module_slots = 4,
  --     -- module_info_icon_shift = { 0, 1.7 },
  --     -- module_info_icon_scale = 1,
  --   },
  --   allowed_effects = { "consumption", "speed", "productivity", "pollution" },
  -- },
  -- -- FIXME: Move these to other files
  -- {
  --   type = "recipe",
  --   name = "kr-singularity",
  --   icon = "__Krastorio2Assets__/icons/entities/intergalactic-transceiver.png",
  --   icon_size = 64,
  --   icon_mipmaps = 4,
  --   flags = { "hidden" },
  --   category = "kr-singularity",
  --   ingredients = { { type = "fluid", name = "matter", amount = 100 } },
  --   results = { { "kr-void", 0 } },
  -- },
  {
    type = "recipe",
    name = "singularity-tech-card",
    category = "kr-singularity",
    energy_required = 20,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "blank-tech-card", 15 },
      { "charged-matter-stabilizer", 5 },
      { "ai-core", 5 },
    },
    results = {
      { "singularity-tech-card", 5 },
      { type = "item", name = "matter-stabilizer", amount = 5, probability = 0.9 },
    },
    main_product = "singularity-tech-card",
  },
  { type = "recipe-category", name = "kr-singularity" },
})
